export const selectWallets = (state) => state.pp.wallets;
export const selectEvent = (state) => state.pp.event;
export const selectMessage = (state) => state.pp.message;
export const selectSeed = (state) => state.pp.seed;
export const selectUtxo = (state) => state.pp.utxo;
export const selectNetwork = (state) => state.pp.network;
export const selectFees = (state) => state.pp.fees;
export const selectQuery = (state) => state.pp.query;
export const selectReady = (state) => state.pp.network && state.pp.network.sync_progress.status === 'ready';
export const selectSyncing = (state) => state.pp.network && state.pp.network.sync_progress.status === 'syncing';
export const selectConnecting = (state) => state.pp.network && state.pp.network.sync_progress.status === 'not_responding';
