version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.33.0
    environment:
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
      NETWORK:
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    networks:
      - test

  cardano-wallet:
    image: inputoutput/cardano-wallet:2022.1.18
    volumes:
      - wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /config/${NETWORK}/genesis-byron.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    networks:
      - test
  
  cardano-nodejs:
    image: kitajchuk/cardano-nodejs:1.33.0
    environment:
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
    volumes:
      - node-ipc:/ipc
      - ./app:/app
    ports:
      - 8888:8888
    entrypoint: ["nodemon", "/app/index.js"]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    networks:
      - test

networks:
  test:

volumes:
  node-mainnet-db:
  node-testnet-db:
  node-alonzo-purple-db:
  wallet-mainnet-db:
  wallet-testnet-db:
  wallet-alonzo-purple-db:
  node-ipc:
  node-config:
